package com.user.po;

public class EmallUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emall_user.userID
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emall_user.userName
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emall_user.userPassword
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emall_user.userEmail
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    private String useremail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emall_user.userID
     *
     * @return the value of emall_user.userID
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emall_user.userID
     *
     * @param userid the value for emall_user.userID
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emall_user.userName
     *
     * @return the value of emall_user.userName
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emall_user.userName
     *
     * @param username the value for emall_user.userName
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emall_user.userPassword
     *
     * @return the value of emall_user.userPassword
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emall_user.userPassword
     *
     * @param userpassword the value for emall_user.userPassword
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emall_user.userEmail
     *
     * @return the value of emall_user.userEmail
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emall_user.userEmail
     *
     * @param useremail the value for emall_user.userEmail
     *
     * @mbggenerated Fri May 12 12:22:49 CST 2017
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }
}